### ISSUE TITLE
DeprecationWarning: Buffer() is deprecated due to security and usability issues on publish

### ISSUE THREAD

**Issue by Eventyret** [HaaLeo/publish-vscode-extension#11]
| publish-vscode-extension Version | Operating System |
| -------------------------------------- | ---------------- |
|                      v0                  |   Mac               |

# Description
Getting this error when it's trying to publish to Marketplace
```bash
Publish the Extension
  (node:1562) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
  Publishing eventyret.bootstrap-4-cdn-snippet@1.12.0...
Error: Error: Failed request: (401)
    at RestClient.<anonymous> (/home/runner/work/_actions/HaaLeo/publish-vscode-extension/v0/dist/index.js:61857:31)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/HaaLeo/publish-vscode-extension/v0/dist/index.js:61661:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Note here is that I'm publishing to open vsx and also a marketplace.
Open VSX works fine but it does not publish to Microsoft marketplace

## Expected Behavior

Publish without error

## Actual Behavior

# Steps to Reproduce

1. Should be just by trying to use the extensions

Thank you again for an amazing plugin!

**Comment by HaaLeo** [comment]
This issue is a duplicate of #4. The deprecation warning of `Buffer()` occurs due to a dependency of the vsce package but is not the cause for the error. Please check on that issue for further details to resolve this.

**Comment by LucasFA** [comment]
Mh, weird, I run into this after so much time
<details><summary>Spoiler</summary>
<pre><code>
Run HaaLeo/publish-vscode-extension@v1
  with:
    pat: ***
    registryUrl: https://marketplace.visualstudio.com/
    extensionFile: myextension-0.7.5.vsix
    packagePath: ./
    yarn: false
    dryRun: false
    noVerify: false
    preRelease: false
    dependencies: true
    skipDuplicate: false
Specifically, running GitHub Action HaaLeo/publish-vscode-extension@v1.5.0.
Package the Extension
  The extension was already packaged. Skip packaging.
Publish the Extension
  (node:1901) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
  (Use `node --trace-deprecation ...` to show where the warning was created)
</pre></code>
</details>
