### ISSUE TITLE
Question: how to workaround or fix Error: package@version already exists. Version number cannot be the same.

### ISSUE THREAD

**Issue by Maximetinu** [HaaLeo/publish-vscode-extension#15]
Hi! 

I have a couple of questions about how to use this action. I'm getting this issue because my repo already has a package.json that specifies a version number:

![image](https://user-images.githubusercontent.com/16073309/143785576-c13571db-eba7-43ff-8819-81736da67c29.png)

I was expecting the action to automagically bump the version at package.json with my new release tag and pushing a commit with that change to my repo. What is the right way to do it?

Sorry if it's a newbie question. This is the first GH Action I'm using and I'm not a hardcore VS Extension developer neither 😅

P.S: I also got this error because the `npm ci` command was missing a package-lock.json file. I don't have one, so I removed it. I guess it is fine, right?

![image](https://user-images.githubusercontent.com/16073309/143785938-7f541b98-9a7a-4865-8fe2-ef10a21c22f5.png)

For reference, this is the repo I'm trying to use this action at: https://github.com/Maximetinu/Sublime-Text-Monokai-theme-for-Visual-Studio-Code

**Comment by HaaLeo** [comment]
Hi @Maximetinu thx for reaching out. Regarding your questions:
> I was expecting the action to automagically bump the version at package.json with my new release tag and pushing a commit with that change to my repo. What is the right way to do it?

_No_, the action does not do that for you. Actually it also cannot do that since it does not know whether your release is a major, minor or patch. I recommend you to do that using the [`npm version`](https://docs.npmjs.com/cli/v6/commands/npm-version) command. When releasing a new version of your extension you should try to adher to [semantic versioning](https://semver.org) to clearly communicate to your extension users what they can expect to change. 

>P.S: I also got this error because the npm ci command was missing a package-lock.json file. I don't have one, so I removed it. I guess it is fine, right?

I recommend you to add the [`package-lock.json`](https://docs.npmjs.com/cli/v6/configuring-npm/package-lock-json) to your repository. IMHO this is a best practice.
If for whatever reason you do not want to add this file to your repository you can also just replace `npm ci` with `npm i`. However, I discourage that.

I hope this answers your questions. If not feel free to comment below or open a new issue.
